apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: platform-cluster-ca
spec:
  secretName: platform-cluster-ca-cert
  issuerRef:
    name: global-issuer
  commonName: "ca.self-signer.cert-manager"
  isCA: true
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    strimzi.io/cluster: platform
    strimzi.io/kind: Kafka
  name: platform-cluster-ca-cert
data:
  ca.crt:
  tls.key:
  tls.crt:
type: Opaque