kind: Secret
apiVersion: v1
metadata:
  name: platform-cluster-ca-cert
data:
  ca.password: passwd
type: kubernetes.io/tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: platform-cluster-ca-cert
spec:
  secretName: platform-cluster-ca-cert
  issuerRef:
    name: global-issuer
    kind: ClusterIssuer
  commonName: "ca.self-signer.cert-manager"
  isCA: false
  usages:
    - server auth
  secretTemplate:
    labels:
      strimzi.io/cluster: platform
      strimzi.io/kind: Kafka
  keystores:
    pkcs12:
      create: true
      passwordSecretRef:
        name: platform-cluster-ca-cert
        key: ca.password
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: platform-cluster-ca
spec:
  secretName: platform-cluster-ca
  issuerRef:
    name: global-issuer
    kind: ClusterIssuer
  commonName: "ca.self-signer.cert-manager"
  isCA: true
  secretTemplate:
    labels:
      strimzi.io/cluster: platform
      strimzi.io/kind: Kafka
