apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kafka-listener
spec:
  dnsNames:
    - platform-kafka-bootstrap.kafka.svc.cluster.local
    - broker-0.platform-kafka-brokers.kafka.svc.cluster.local
    - broker-1.platform-kafka-brokers.kafka.svc.cluster.local
    - broker-2.platform-kafka-brokers.kafka.svc.cluster.local
  issuerRef:
    name: global-issuer
    kind: ClusterIssuer
  secretName: kafka-listener-cert
  usages:
    - server auth