# See argocd/platform-root.yaml for overrides
clusterRouterDomain: apps.example.cluster.com
serviceAccountToken: eyREPLACEME

gitHost: https://github.com
gitOrg: contract-first-idp
gitRef: main
gitToken: ghp_REPLACEME

eclipseClientId: eclipse-che-git-app-id
eclipseClientSecret: eclipse-che-git-app-secret

authClientSecret: CjrBujp80h6lWt7PEesM4tklZaqTfPal
authSessionSecret: Q72XbDKY8IcNSNzAQjVwa3xmh4lfdvzG

dbUsername: postgres
dbPassword: dbpw

kafkaOidcClientId: kafka
kafkaOidcClientSecret: kafka-oidc-client-secret