apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: default
  source:
    repoURL: "{{ .Values.gitHost }}/{{ .Values.gitOrg }}/platform-components.git"
    path: charts/kafka
    targetRevision: "{{ .Values.gitRef }}"
    helm:
      parameters:
        - name: clusterRouterDomain
          value: "{{ .Values.clusterRouterDomain }}"
        - name: kafka.oidc.clientId
          value: "{{ .Values.kafkaOidcClientId }}"
        - name: kafka.oidc.secret
          value: "{{ .Values.kafkaOidcClientSecret }}"
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m
